name: Jekyll site CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Ensure the `run` script is runnable
      run: chmod +x ${{ github.workspace }}/_docker/run.sh
    - name: Build the site in the jekyll/builder container
        # Replace ednutting/github-pages-agda with your "$dockerUsername/$dockerRepo" below
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        ednutting/github-pages-agda:latest /srv/jekyll/_docker/run.sh
    - name: Deploy the site to master branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: master
